# =============================================================================
# cli.py — Interactive CLI Menu for News Digest
# =============================================================================
#
# When a user types `news-digest` with no arguments, this module powers
# the interactive menu that appears.  It lets subscribed users manage
# their digest without needing to remember command-line flags.
#
# Menu options:
#   1) Send digest now
#   2) Preview digest (dry run)
#   3) Change news sources
#   4) Change email address
#   5) Change app password
#   6) Change delivery schedule
#   7) View current status
#   8) Uninstall
#   9) Exit
#
# Dependencies:
#   newsdigest.config   — current settings
#   newsdigest.sources   — source registry
#   newsdigest.scheduler — schedule management
#   setup_wizard         — reuses formatting helpers
# =============================================================================

"""
Interactive CLI menu for managing the News Digest installation.
"""

import importlib
import getpass
import os
import re
import subprocess
import sys
from pathlib import Path

from newsdigest.paths import venv_python_path

# ---------------------------------------------------------------------------
# Terminal formatting (matches style in setup_wizard.py)
# ---------------------------------------------------------------------------

BOLD = "\033[1m"
DIM = "\033[2m"
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
CYAN = "\033[0;36m"
BLUE = "\033[0;34m"
WHITE = "\033[1;37m"
NC = "\033[0m"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = PROJECT_ROOT / ".env"
VENV_PYTHON = venv_python_path(PROJECT_ROOT)
WINDOWS_WRAPPER = Path.home() / "AppData" / "Local" / "NewsDigest" / "bin" / "news-digest.cmd"

W = 55  # Display width for divider lines


def _clear() -> None:
    """Clear the terminal screen (only when connected to a real terminal)."""
    if sys.stdout.isatty():
        print("\033[2J\033[H", end="", flush=True)


def _header(title: str) -> None:
    """Display the main menu banner with prominent styling."""
    print()
    print(f"  {CYAN}{'━' * W}{NC}")
    print(f"  {WHITE}  📰  {title}{NC}")
    print(f"  {CYAN}{'━' * W}{NC}")


def _banner(text: str) -> None:
    """Display a sub-screen header."""
    print()
    print(f"  {CYAN}{'─' * W}{NC}")
    print(f"  {BOLD}  {text}{NC}")
    print(f"  {CYAN}{'─' * W}{NC}")
    print()


def _success(text: str) -> None:
    print(f"  {GREEN}✔{NC}  {text}")


def _warn(text: str) -> None:
    print(f"  {YELLOW}⚠{NC}  {text}")


def _fail(text: str) -> None:
    print(f"  {RED}✘{NC}  {text}")


def _info(text: str) -> None:
    print(f"  {BLUE}ℹ{NC}  {text}")


def _pause() -> None:
    """Wait for user to press Enter before returning to the menu."""
    print()
    input(f"  {DIM}Press Enter to continue ↵{NC} ")


def _reload_config():
    """Force-reload config module so it picks up .env changes."""
    import newsdigest.config
    # Clear cached env vars so load_dotenv re-reads the file
    for key in ("SMTP_EMAIL", "SMTP_APP_PASSWORD", "RECIPIENT_EMAIL",
                "SELECTED_SOURCES", "SCHEDULE_TIME"):
        os.environ.pop(key, None)
    importlib.reload(newsdigest.config)
    return newsdigest.config


def _protect_env_file() -> None:
    """Restrict .env readability on POSIX systems."""
    if os.name == "nt" or not ENV_FILE.exists():
        return

    try:
        ENV_FILE.chmod(0o600)
    except OSError:
        _warn("Couldn't tighten permissions for .env.")


def _setup_command() -> str:
    """Return the preferred user-facing setup command for this OS."""
    if os.name == "nt":
        return "news-digest setup"
    return "./start.sh"


def _read_env() -> dict[str, str]:
    """Read the current .env file into a dict."""
    env = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                env[key.strip()] = value.strip()
    return env


def _write_env(env: dict[str, str]) -> None:
    """Write the env dict back to the .env file."""
    lines = ["# News Digest Configuration",
             f"# Generated by setup wizard — re-run {_setup_command()} to change"]
    for key in ("SMTP_EMAIL", "SMTP_APP_PASSWORD", "RECIPIENT_EMAIL",
                "SELECTED_SOURCES", "SCHEDULE_TIME"):
        if key in env:
            lines.append(f"{key}={env[key]}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    _protect_env_file()


# =============================================================================
# Menu actions
# =============================================================================

def action_send_now() -> None:
    """Send the digest immediately."""
    _banner("Sending Digest")
    result = subprocess.run(
        [str(VENV_PYTHON), str(PROJECT_ROOT / "main.py")],
        cwd=str(PROJECT_ROOT),
    )
    if result.returncode != 0 and result.returncode != 1:
        _fail("Something went wrong — see error above.")
    _pause()


def action_preview() -> None:
    """Preview the digest without sending."""
    _banner("Digest Preview (Dry Run)")
    subprocess.run(
        [str(VENV_PYTHON), str(PROJECT_ROOT / "main.py"), "--dry-run"],
        cwd=str(PROJECT_ROOT),
    )
    _pause()


def action_change_sources() -> None:
    """Let the user re-pick their news sources."""
    from newsdigest.sources import AVAILABLE_SOURCES

    _banner("Change News Sources")

    env = _read_env()
    current = [s.strip() for s in env.get("SELECTED_SOURCES", "").split(",") if s.strip()]

    for i, source in enumerate(AVAILABLE_SOURCES, start=1):
        marker = f"{GREEN}✔{NC}" if source.key in current else " "
        print(f"    {marker}  {BOLD}[{i}]{NC}  {source.name}")
        print(f"              {DIM}{source.description}{NC}")
    print()

    while True:
        print(f"  {DIM}Enter numbers separated by spaces, or 'all'{NC}")
        print(f"  {DIM}Example: 1 3 4{NC}")
        print()
        raw = input(f"  {BOLD}Sources ▸{NC} ").strip()

        if not raw:
            _warn("Please select at least one source.")
            print()
            continue

        if raw.lower() == "all":
            selected = list(AVAILABLE_SOURCES)
            break

        try:
            nums = [int(x) for x in raw.split()]
        except ValueError:
            _warn("Please enter numbers only (e.g., 1 3 4).")
            print()
            continue

        invalid = [n for n in nums if n < 1 or n > len(AVAILABLE_SOURCES)]
        if invalid:
            _warn(f"Invalid choice(s): {invalid}. Choose from 1–{len(AVAILABLE_SOURCES)}.")
            print()
            continue

        if not nums:
            _warn("Please select at least one source.")
            print()
            continue

        seen = set()
        selected = []
        for n in nums:
            if n not in seen:
                seen.add(n)
                selected.append(AVAILABLE_SOURCES[n - 1])
        break

    env["SELECTED_SOURCES"] = ",".join(s.key for s in selected)
    _write_env(env)

    print()
    _success("Sources updated:")
    for s in selected:
        print(f"       • {s.name}")
    _pause()


def action_change_email() -> None:
    """Change the sender/recipient Gmail address."""
    _banner("Change Email Address")

    env = _read_env()
    current = env.get("SMTP_EMAIL", "(not set)")
    print(f"  {BOLD}Current email:{NC} {current}")
    print()

    email_regex = re.compile(r"^[a-zA-Z0-9._%+-]+@gmail\.com$")

    while True:
        email = input(f"  {BOLD}New Gmail address (or 'cancel'):{NC} ").strip()

        if email.lower() == "cancel":
            _info("Cancelled — email unchanged.")
            _pause()
            return

        if not email:
            _warn("Email cannot be empty.")
            continue

        if not email_regex.match(email):
            _warn("Please enter a valid Gmail address (must end with @gmail.com).")
            continue

        break

    env["SMTP_EMAIL"] = email
    env["RECIPIENT_EMAIL"] = email
    _write_env(env)

    _success(f"Email updated to {BOLD}{email}{NC}")
    _warn("If this is a different Gmail account, you'll also need a new App Password.")
    _pause()


def action_change_password() -> None:
    """Change the Gmail App Password."""
    _banner("Change App Password")

    print(f"  To get a new App Password:")
    print(f"    1. Go to {BOLD}https://myaccount.google.com/apppasswords{NC}")
    print(f"    2. Create a new password named 'News Digest'")
    print(f"    3. Copy the 16-character password")
    print(f"  {DIM}Your typing will be hidden for privacy.{NC}")
    print()

    while True:
        password = getpass.getpass("  New App Password (or 'cancel'): ").strip()

        if password.lower() == "cancel":
            _info("Cancelled — password unchanged.")
            _pause()
            return

        password = password.replace(" ", "")

        if not password:
            _warn("Password cannot be empty.")
            continue

        if len(password) != 16:
            _warn(f"App Passwords are exactly 16 characters. You entered {len(password)}.")
            continue

        if not password.isalpha():
            _warn("App Passwords contain only letters (no numbers or symbols).")
            continue

        break

    env = _read_env()
    env["SMTP_APP_PASSWORD"] = password
    _write_env(env)

    _success("App Password updated.")
    _pause()


def action_change_schedule() -> None:
    """Change or toggle the delivery schedule."""
    from newsdigest.scheduler import (
        install_schedule, uninstall_schedule, is_schedule_installed, detect_os,
    )

    _banner("Change Delivery Schedule")

    env = _read_env()
    current_time = env.get("SCHEDULE_TIME", "")
    scheduled = is_schedule_installed()

    if scheduled and current_time:
        print(f"  {BOLD}Current schedule:{NC} Daily at {GREEN}{current_time}{NC}")
    else:
        print(f"  {BOLD}Current schedule:{NC} {DIM}not set (manual only){NC}")
    print()

    print(f"    {BOLD}[1]{NC}  Set a new delivery time")
    if scheduled:
        print(f"    {BOLD}[2]{NC}  Turn off automatic delivery")
    print(f"    {DIM}[0]  Cancel{NC}")
    print()

    choice = input(f"  {BOLD}▸{NC} ").strip()

    if choice == "0":
        _info("Cancelled — schedule unchanged.")
        _pause()
        return

    if choice == "2" and scheduled:
        msg = uninstall_schedule()
        env["SCHEDULE_TIME"] = ""
        _write_env(env)
        _success(msg)
        _pause()
        return

    if choice == "1":
        current_os = detect_os()
        if current_os == "unknown":
            _fail("Automatic scheduling is not supported on this OS.")
            _pause()
            return

        print()
        print(f"  {DIM}Enter time in 24-hour format (e.g., 08:00, 18:30){NC}")
        print()

        while True:
            time_input = input(f"  {BOLD}Time [08:00] ▸{NC} ").strip()

            if not time_input:
                time_input = "08:00"

            match = re.match(r"^(\d{1,2}):(\d{2})$", time_input)
            if not match:
                _warn("Please use HH:MM format (e.g., 08:00, 14:30).")
                continue

            hour = int(match.group(1))
            minute = int(match.group(2))

            if hour < 0 or hour > 23:
                _warn("Hour must be between 0 and 23.")
                continue
            if minute < 0 or minute > 59:
                _warn("Minute must be between 0 and 59.")
                continue

            break

        try:
            msg = install_schedule(hour, minute)
            env["SCHEDULE_TIME"] = f"{hour:02d}:{minute:02d}"
            _write_env(env)
            _success(msg)
        except (RuntimeError, ValueError) as e:
            _fail(str(e))

        _pause()
        return

    _warn("Invalid choice.")
    _pause()


def action_status() -> None:
    """Show current installation and configuration status."""
    from newsdigest.sources import get_source_by_key
    from newsdigest.scheduler import is_schedule_installed

    _banner("Status")

    env = _read_env()
    L = 18  # label column width for alignment

    # Install location
    print(f"  {BOLD}{'Install path:':<{L}}{NC} {PROJECT_ROOT}")

    # Python version
    try:
        pyver = subprocess.run(
            [str(VENV_PYTHON), "--version"],
            capture_output=True, text=True,
        ).stdout.strip()
        print(f"  {BOLD}{'Python:':<{L}}{NC} {pyver}")
    except FileNotFoundError:
        print(f"  {BOLD}{'Python:':<{L}}{NC} {RED}not found{NC}")

    # Email
    email = env.get("SMTP_EMAIL", "")
    if email:
        print(f"  {BOLD}{'Email:':<{L}}{NC} {email}")
    else:
        print(f"  {BOLD}{'Email:':<{L}}{NC} {RED}not configured{NC}")

    # Sources
    sources_raw = env.get("SELECTED_SOURCES", "")
    source_keys = [s.strip() for s in sources_raw.split(",") if s.strip()]
    if source_keys:
        names = []
        for key in source_keys:
            src = get_source_by_key(key)
            names.append(src.name if src else key)
        print(f"  {BOLD}{'Sources:':<{L}}{NC} {', '.join(names)}")
    else:
        print(f"  {BOLD}{'Sources:':<{L}}{NC} {RED}none selected{NC}")

    # Schedule
    sched_time = env.get("SCHEDULE_TIME", "")
    scheduled = is_schedule_installed()
    if scheduled and sched_time:
        print(f"  {BOLD}{'Schedule:':<{L}}{NC} {GREEN}✔ active{NC} — daily at {sched_time}")
    elif sched_time:
        print(f"  {BOLD}{'Schedule:':<{L}}{NC} {YELLOW}⚠ configured but not active{NC}")
    else:
        print(f"  {BOLD}{'Schedule:':<{L}}{NC} {DIM}off (manual only){NC}")

    # Last sent
    state_file = PROJECT_ROOT / ".last_sent"
    if state_file.exists():
        import datetime
        mtime = state_file.stat().st_mtime
        dt = datetime.datetime.fromtimestamp(mtime)
        print(f"  {BOLD}{'Last sent:':<{L}}{NC} {dt.strftime('%Y-%m-%d %H:%M')}")
    else:
        print(f"  {BOLD}{'Last sent:':<{L}}{NC} {DIM}never{NC}")

    _pause()


def action_uninstall() -> None:
    """Uninstall News Digest completely."""
    _banner("Uninstall News Digest")

    print(f"  {RED}{BOLD}⚠  This action cannot be undone.{NC}")
    print()
    print(f"  The following will be permanently removed:")
    print(f"    •  Daily schedule {DIM}(if active){NC}")
    print(f"    •  All project files in {BOLD}{PROJECT_ROOT}{NC}")
    print(f"    •  The {BOLD}news-digest{NC} command")
    print()

    answer = input(f"  {BOLD}Type 'yes' to confirm (or anything else to cancel):{NC} ").strip().lower()
    if answer not in ("y", "yes"):
        _info("Cancelled — nothing was removed.")
        return

    print()

    # Remove schedule
    from newsdigest.scheduler import is_schedule_installed, uninstall_schedule
    if is_schedule_installed():
        print(f"  {DIM}Removing daily schedule...{NC}")
        uninstall_schedule()
        _success("Schedule removed.")
    else:
        print(f"  {DIM}No schedule to remove.{NC}")

    # Detect symlink location before we delete files
    import shutil
    link_path = None
    candidates = [
        "/usr/local/bin/news-digest",
        str(Path.home() / ".local" / "bin" / "news-digest"),
    ]
    if os.name == "nt":
        candidates.insert(0, str(WINDOWS_WRAPPER))

    for candidate in candidates:
        if os.path.islink(candidate):
            link_path = candidate
            break
        if os.name == "nt" and Path(candidate).exists():
            link_path = candidate
            break

    # Remove install directory
    print(f"  {DIM}Removing {PROJECT_ROOT}...{NC}")
    shutil.rmtree(PROJECT_ROOT, ignore_errors=True)
    _success("Files removed.")

    # Remove symlink
    if link_path:
        print(f"  {DIM}Removing command: {link_path}{NC}")
        try:
            os.remove(link_path)
            _success("Command removed.")
        except OSError:
            if os.name == "nt":
                _warn(f"Could not remove {link_path}. Delete it manually if needed.")
            else:
                _warn(f"Could not remove {link_path} (may need sudo)")
                print(f"  {DIM}Run: sudo rm {link_path}{NC}")

    print()
    _success(f"{BOLD}News Digest has been completely uninstalled.{NC}")
    print(f"  {DIM}To reinstall, run the release installer again.{NC}")
    print()

    sys.exit(0)


def action_send_force() -> None:
    """Force-send the digest even if already sent today."""
    _banner("Force Send Digest")
    subprocess.run(
        [str(VENV_PYTHON), str(PROJECT_ROOT / "main.py"), "--force"],
        cwd=str(PROJECT_ROOT),
    )
    _pause()


# =============================================================================
# Main menu loop
# =============================================================================

MENU_OPTIONS = [
    ("1", "Send digest now",           action_send_now),
    ("2", "Preview digest (dry run)",  action_preview),
    ("3", "Force re-send digest",      action_send_force),
    ("4", "Change news sources",       action_change_sources),
    ("5", "Change email address",      action_change_email),
    ("6", "Change app password",       action_change_password),
    ("7", "Change delivery schedule",  action_change_schedule),
    ("8", "View status",              action_status),
    ("9", "Uninstall",                action_uninstall),
    ("0", "Exit",                     None),
]


def show_menu() -> None:
    """Display the interactive menu and handle user choices in a loop."""
    # Ensure stdin reads from terminal if piped
    if not sys.stdin.isatty():
        try:
            sys.stdin = open("/dev/tty", "r")
        except OSError:
            pass

    while True:
        _clear()
        _header("News Digest")

        # ── Status bar ──────────────────────────────────────────
        env = _read_env()
        email = env.get("SMTP_EMAIL", "")
        sources_raw = env.get("SELECTED_SOURCES", "")
        source_count = len([s for s in sources_raw.split(",") if s.strip()])
        sched = env.get("SCHEDULE_TIME", "")

        if email:
            parts = [email]
            if source_count:
                parts.append(f"{source_count} source{'s' if source_count != 1 else ''}")
            if sched:
                parts.append(f"Daily at {sched}")
            else:
                parts.append("Manual delivery")
            print(f"  {DIM}{'  ·  '.join(parts)}{NC}")

        # ── Send ────────────────────────────────────────────────
        print()
        print(f"  {CYAN}── Send {'─' * (W - 9)}{NC}")
        print(f"    {BOLD}[1]{NC}  Send digest now")
        print(f"    {BOLD}[2]{NC}  Preview digest {DIM}(dry run){NC}")
        print(f"    {BOLD}[3]{NC}  Force re-send")

        # ── Settings ────────────────────────────────────────────
        print()
        print(f"  {CYAN}── Settings {'─' * (W - 13)}{NC}")
        print(f"    {BOLD}[4]{NC}  News sources")
        print(f"    {BOLD}[5]{NC}  Email address")
        print(f"    {BOLD}[6]{NC}  App password")
        print(f"    {BOLD}[7]{NC}  Delivery schedule")

        # ── System ──────────────────────────────────────────────
        print()
        print(f"  {CYAN}{'─' * W}{NC}")
        print(f"    {BOLD}[8]{NC}  Status")
        print(f"    {RED}[9]  Uninstall{NC}")
        print(f"    {DIM}[0]  Exit{NC}")

        print()
        choice = input(f"  {BOLD}▸{NC} ").strip()

        if choice == "0":
            _clear()
            print()
            print(f"  {DIM}👋 Goodbye!{NC}")
            print()
            break

        matched = False
        for key, _, action in MENU_OPTIONS:
            if choice == key and action is not None:
                action()
                matched = True
                break

        if not matched and choice != "0":
            _warn(f"Invalid choice: '{choice}'. Please enter a number 0–9.")
            _pause()


def main() -> None:
    """Entry point for the interactive CLI menu."""
    show_menu()


if __name__ == "__main__":
    main()
